spring.application.name=backend

# Configuração da base de dados PostgreSQL no Azure
spring.datasource.url=jdbc:postgresql://projetos-pessoais.postgres.database.azure.com:5432/postgres?sslmode=require
spring.datasource.username=taskflowadmin
spring.datasource.password=T@askflow

# Dialecto e driver
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Recomendações para desenvolvimento
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


